# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

stages:
- stage: Build
  displayName: Build image
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(c6d7b624-c28d-4c76-9e34-62d9dae81dc0)'
    azureContainerRegistry: '{"loginServer":"akstesting1234.azurecr.io", "id" : "/subscriptions/c6d7b624-c28d-4c76-9e34-62d9dae81dc0/resourceGroups/aks-rg1/providers/Microsoft.ContainerRegistry/registries/akstesting1234"}'
    action: 'Run a Docker Compose command'
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
